### ISSUE TITLE
Pedantic style comments

### ISSUE THREAD

**Issue by Xe** [Decagon/Pedant#1]
``` javascript
var punctuation = ",.!;";
var quotes = "\"\'";
```

Prefer

``` javascript
var punctuation = [',', '.', '!', ';', ';', '"'];
var quotes = ['"', "'"];
```

Even though a string can be indexed in JS by integer values, this change still makes it more clear that you are using the `punctuation` and `quotes` values as arrays, not strings (generally a single quote is preferable for _character literals_, but not for strings).

**Comment by alexyorke** [comment]
This is a very good idea, as it makes things a lot clearer, avoids the useless call to split(""), and allows expandability in the future (as we can add multiple punctuation symbols per element, and have it detect those tokens.)

Thanks!
