### ISSUE TITLE
Contractions in parentheses are mistaken for quotes

### ISSUE THREAD

**Issue by dhasenan** [Decagon/Pedant#3]
``` JavaScript
pedant.validate("She sang (as I'm sure you know). He dances. (Poorly.)");
```

This produces the following output:

```
QuoteError: max quote length of 20 exceeded at index 53 (quote started at index 14)
```

"I'm" is not a quote.

**Comment by alexyorke** [comment]
Thanks for finding these issues! I'll have to fix the tokenizer such that it accepts contractions (I need to add some unit tests too.) This will be closed as soon as I can fix it.
