### ISSUE TITLE
Parenthetical sentences must end with a space

### ISSUE THREAD

**Issue by dhasenan** [Decagon/Pedant#4]
```
pedant.validate("He dances. (Poorly.)");
pedant.validate("He dances. (Poorly. )");
```

The first example produces an error:

```
... (Poorly.)...
           ^
PunctuationError: no space after punctuation at index 18:
```

The second example produces no error.

The first example should not produce an error. The second should produce an error stating that there should not be a space between punctuation and the closing parenthesis.

**Comment by alexyorke** [comment]
This one might be a little tricky to fix, but it is a problem though. I'll get to work fixing this one. Thanks again for finding this!

**Comment by alexyorke** [comment]
This should be fixed. Let me know if any regressions occur!
